/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.69
 * Generated at: 2023-03-18 07:03:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.util.*;
import java.util.*;
import java.text.*;
import java.util.Date;
import java.sql.*;
import com.oreilly.servlet.*;
import java.lang.*;
import java.text.SimpleDateFormat;
import java.io.*;
import javax.servlet.*;
import javax.servlet.http.*;
import java.util.*;
import java.security.Key;
import java.util.Random;
import javax.crypto.Cipher;
import javax.crypto.spec.SecretKeySpec;
import org.bouncycastle.util.encoders.Base64;
import java.util.Random;
import java.io.PrintStream;
import java.io.FileOutputStream;
import java.io.FileInputStream;
import java.security.DigestInputStream;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.io.BufferedInputStream;

public final class Admin_005fViewCCRequest_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/connect.jsp", Long.valueOf(1540290754000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("com.oreilly.servlet");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("java.text");
    _jspx_imports_packages.add("java.lang");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.io.PrintStream");
    _jspx_imports_classes.add("java.io.BufferedInputStream");
    _jspx_imports_classes.add("org.bouncycastle.util.encoders.Base64");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.security.MessageDigest");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("javax.crypto.spec.SecretKeySpec");
    _jspx_imports_classes.add("java.io.FileOutputStream");
    _jspx_imports_classes.add("java.util.Random");
    _jspx_imports_classes.add("java.io.FileInputStream");
    _jspx_imports_classes.add("javax.crypto.Cipher");
    _jspx_imports_classes.add("java.security.Key");
    _jspx_imports_classes.add("java.security.DigestInputStream");
    _jspx_imports_classes.add("java.math.BigInteger");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<title></title>\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Connection connection = null;
 	try {
     

	  	Class.forName("com.mysql.jdbc.Driver");	
		connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/cc_fraud","root","root");
      	String sql="";

	}
	catch(Exception e)
	{
		System.out.println(e);
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>Credit Card Request Process</title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/coin-slider.css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/cufon-yui.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/cufon-quicksand.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-1.4.2.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/script.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/coin-slider.min.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("<!--\r\n");
      out.write(".style1 {\r\n");
      out.write("	font-size: 24px;\r\n");
      out.write("	color: #FF0000;\r\n");
      out.write("}\r\n");
      out.write(".style3 {color: #333333}\r\n");
      out.write(".style4 {\r\n");
      out.write("	color: #660000;\r\n");
      out.write("	font-size: 24px;\r\n");
      out.write("}\r\n");
      out.write(".style5 {color: #2C83B0}\r\n");
      out.write(".style6 {\r\n");
      out.write("	color: #660000;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write(".style7 {color: #660000}\r\n");
      out.write(".style9 {color:#000000}\r\n");
      out.write("\r\n");
      out.write(".style12 {color: #009999}\r\n");
      out.write(".style44 {color:#FF3300;\r\n");
      out.write("		font-size: 14px;}\r\n");
      out.write(".style45 {color: #2C83B0;\r\n");
      out.write("		font-size: 14px;}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"main\">\r\n");
      out.write("  <div class=\"header\">\r\n");
      out.write("    <div class=\"header_resize\">\r\n");
      out.write("      <div class=\"logo\">\r\n");
      out.write("        <h1 align=\"center\"><a href=\"index.html\" class=\"style1\">Credit card fraud detection using AdaBoost and majority voting</a></h1>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"menu_nav\">\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li class=\"active\"><a href=\"index.html\"><span>Home Page</span></a></li>\r\n");
      out.write("          <li><a href=\"AdminLogin.jsp\"><span>Bank Admin</span></a></li>\r\n");
      out.write("          <li><a href=\"EcommerceLogin.jsp\"><span>Ecommerce</span></a></li>\r\n");
      out.write("          <li><a href=\"UserLogin.jsp\"><span>User</span></a></li>\r\n");
      out.write("          <li><a href=\"#\"><span>Contact Us</span></a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"clr\"></div>\r\n");
      out.write("      <div class=\"slider\">\r\n");
      out.write("        <div id=\"coin-slider\"> <a href=\"#\"><img src=\"images/slide1.jpg\" width=\"935\" height=\"285\" alt=\"\" /> </a> <a href=\"#\"><img src=\"images/slide2.jpg\" width=\"935\" height=\"285\" alt=\"\" /> </a> <a href=\"#\"><img src=\"images/slide3.jpg\" width=\"935\" height=\"285\" alt=\"\" /> </a> </div>\r\n");
      out.write("        <div class=\"clr\"></div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"clr\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"content\">\r\n");
      out.write("    <div class=\"content_resize\">\r\n");
      out.write("      <div class=\"mainbar\">\r\n");
      out.write("        <div class=\"article\"> \r\n");
      out.write("          <h2 class=\"style4\" style=\"color:#CC6600\">Credit Card Requests from <span class=\"style5\">");
      out.print((String)application.getAttribute("adbank"));
      out.write("</span>'s Users....</h2>\r\n");
      out.write("          <div class=\"clr\"></div>          \r\n");
      out.write("          <div class=\"post_content\">\r\n");
      out.write("            <p>&nbsp;</p>\r\n");
      out.write("          <p>&nbsp;</p>\r\n");
      out.write("          <table width=\"570\" border=\"1\" bgcolor=\"#FFFFFF\" align=\"center\"  cellpadding=\"0\" cellspacing=\"0\"  \">\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td  width=\"106\"  valign=\"middle\" height=\"25\" style=\"color: #2c83b0;\"><div align=\"center\" class=\"style56 style57 style6\">ID</div></td>\r\n");
      out.write("              \r\n");
      out.write("			  <td  width=\"250\" valign=\"middle\" height=\"25\" style=\"color: #2c83b0;\"><div align=\"center\" class=\"style7 style57 style56\"><b>Account Holder Name</b></div></td>\r\n");
      out.write("			  <td  width=\"199\" valign=\"middle\" height=\"25\" style=\"color: #2c83b0;\"><div align=\"center\" class=\"style7 style57 style56\"><b>Credit Limit</b></div></td>\r\n");
      out.write("			  <td  width=\"199\" valign=\"middle\" height=\"25\" style=\"color: #2c83b0;\"><div align=\"center\" class=\"style7 style57 style56\"><b>Cash Limit</b></div></td>\r\n");
      out.write("              <td  width=\"217\" valign=\"middle\" style=\"color: #2c83b0;\"><div align=\"center\" class=\"style7 style57 style56\"><b>Requested Date</b></div></td>\r\n");
      out.write("              <td  width=\"171\" valign=\"middle\" height=\"25\" style=\"color: #2c83b0;\"><div align=\"center\" class=\"style7 style57 style56\"><b>Credit Card Number </b></div></td>\r\n");
      out.write("			  <td  width=\"171\" valign=\"middle\" height=\"25\" style=\"color: #2c83b0;\"><div align=\"center\" class=\"style57 style56 style7\"><b>CRN </b></div></td>\r\n");
      out.write("			  <td  width=\"171\" valign=\"middle\" height=\"25\" style=\"color: #2c83b0;\"><div align=\"center\" class=\"style57 style56 style7\"><b>CVV </b></div></td>\r\n");
      out.write("			  <td  width=\"171\" valign=\"middle\" height=\"25\" style=\"color: #2c83b0;\"><div align=\"center\" class=\"style57 style56 style7\"><b>Card Expiry Date </b></div></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            ");

					  String bank=(String)application.getAttribute("adbank");
					  String s1,s2,s3,s4,s5,s6,s7,s8,s9;
						int i=0,j=1;
						try 
						{
																					
						   	String query="select * from creditcardrequest where b_name='"+bank+"'"; 
						   	Statement st=connection.createStatement();
						   	ResultSet rs=st.executeQuery(query);
					   		while ( rs.next() )
					   		{
								i=rs.getInt(1);
								s1=rs.getString(2);
								s2=rs.getString(3);
								s3=rs.getString(9);
								s4=rs.getString(10);
								s5=rs.getString(12);
								s6=rs.getString(6);
								s7=rs.getString(7);
								s8=rs.getString(8);
								s9=rs.getString(11);
								
								
								
					
      out.write("\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td height=\"57\" align=\"center\"  valign=\"middle\"><div align=\"center\" class=\"style9\">\r\n");
      out.write("                ");
out.println(j);
      out.write("\r\n");
      out.write("              </div></td>\r\n");
      out.write("			  <td height=\"57\" align=\"center\"  valign=\"middle\"><div align=\"center\" class=\"style44\">\r\n");
      out.write("                <b>");
out.println(s2);
      out.write("</b>\r\n");
      out.write("              </div></td>\r\n");
      out.write("			  <td height=\"57\" align=\"center\"  valign=\"middle\"><div align=\"center\" class=\"style9\">\r\n");
      out.write("                ");
out.println(s3);
      out.write("\r\n");
      out.write("              </div></td>\r\n");
      out.write("              <td height=\"57\" align=\"center\"  valign=\"middle\"><div align=\"center\" class=\"style9\">\r\n");
      out.write("                ");
out.println(s4);
      out.write("\r\n");
      out.write("              </div></td>\r\n");
      out.write("              <td align=\"center\"  valign=\"middle\"><div align=\"center\" class=\"style9\">\r\n");
      out.write("                ");
out.println(s5);
      out.write("\r\n");
      out.write("              </div></td>\r\n");
      out.write("             \r\n");
      out.write("              ");

						if(s6.equalsIgnoreCase("Requested"))
						{
						
						
      out.write("\r\n");
      out.write("              <td valign=\"middle\" height=\"57\" title=\"Click to generate Credit Card Number\" style=\"color:#000000;\"align=\"center\"><div align=\"center\">\r\n");
      out.write("                  <div align=\"center\" class=\"style20 style37 style46\"><a href=\"GenerateCreditCardNm.jsp?typebank=");
      out.print(bank);
      out.write("&amp;id=");
      out.print(i);
      out.write("&accountname=");
      out.print(s2);
      out.write("\" class=\"style87 style30 style96 style12\"><b>Generate CC No</b></a></div>\r\n");
      out.write("              </div></td>\r\n");
      out.write("              ");

			  			}
						  else
						{
						
      out.write(" <td width=\"17\" align=\"center\"  valign=\"middle\"><div align=\"center\" class=\"style12\">\r\n");
      out.write("							\r\n");
      out.write("							<b>");
out.println(s6);
      out.write("</b>\r\n");
      out.write("						  </div></td>\r\n");
      out.write("            			 ");
}
      out.write("\r\n");
      out.write("				");

						if(s7.equalsIgnoreCase("Requested"))
						{
						
						
      out.write("\r\n");
      out.write("              <td valign=\"middle\" height=\"57\" title=\"Click to generate Customer Relation Number\" style=\"color:#000000;\"align=\"center\"><div align=\"center\">\r\n");
      out.write("                  <div align=\"center\" class=\"style20 style37 style46\"><a href=\"GenerateCRN.jsp?typebank=");
      out.print(bank);
      out.write("&amp;id=");
      out.print(i);
      out.write("&accountname=");
      out.print(s2);
      out.write("\" class=\"style87 style30 style96 style12\"><b>Generate CRN</b></a></div>\r\n");
      out.write("              </div></td>\r\n");
      out.write("              ");

			  			}
						  else
						{
						
      out.write(" <td width=\"17\" align=\"center\"  valign=\"middle\"><div align=\"center\" class=\"style12\">\r\n");
      out.write("							\r\n");
      out.write("							<b>");
out.println(s7);
      out.write("</b>\r\n");
      out.write("						  </div></td>\r\n");
      out.write("            			 ");
}
      out.write("\r\n");
      out.write("				");

						if(s8.equalsIgnoreCase("Requested"))
						{
						
						
      out.write("\r\n");
      out.write("              <td valign=\"middle\" height=\"57\" title=\"Click to generate Card CVV\" style=\"color:#000000;\"align=\"center\"><div align=\"center\">\r\n");
      out.write("                  <div align=\"center\" class=\"style20 style37 style46\"><a href=\"GenerateCVV.jsp?typebank=");
      out.print(bank);
      out.write("&amp;id=");
      out.print(i);
      out.write("&accountname=");
      out.print(s2);
      out.write("\" class=\"style87 style30 style96 style12\"><b>Generate CVV</b></a></div>\r\n");
      out.write("              </div></td>\r\n");
      out.write("              ");

			  			}
						  else
						{
						
      out.write(" <td width=\"17\" align=\"center\"  valign=\"middle\"><div align=\"center\" class=\"style12\">\r\n");
      out.write("							\r\n");
      out.write("							<b>");
out.println(s8);
      out.write("</b>\r\n");
      out.write("						  </div></td>\r\n");
      out.write("            			 ");
}
      out.write("\r\n");
      out.write("				");

						if(s9.equalsIgnoreCase("Assign"))
						{
						
						
      out.write("\r\n");
      out.write("              <td valign=\"middle\" height=\"57\" title=\"Click to Assign Expiry Date\" style=\"color:#000000;\"align=\"center\"><div align=\"center\">\r\n");
      out.write("                  <div align=\"center\" class=\"style20 style37 style46\"><a href=\"AssignExpDate.jsp?typebank=");
      out.print(bank);
      out.write("&amp;id=");
      out.print(i);
      out.write("&accountname=");
      out.print(s2);
      out.write("\" class=\"style87 style30 style96 style12\"><b>Assign Expiry Date</b></a></div>\r\n");
      out.write("              </div></td>\r\n");
      out.write("              ");

			  			}
						  else
						{
						
      out.write(" <td width=\"17\" align=\"center\"  valign=\"middle\"><div align=\"center\" class=\"style12\">\r\n");
      out.write("							\r\n");
      out.write("							<b>");
out.println(s9);
      out.write("</b>\r\n");
      out.write("						  </div></td>\r\n");
      out.write("            			 ");
}
      out.write("		 \r\n");
      out.write("						 \r\n");
      out.write("						  \r\n");
      out.write("            </tr>\r\n");
      out.write("            ");

						j+=1;}
						
					
				
						connection.close();
					}
					catch(Exception e)
					{
						out.println(e.getMessage());
					}
					
      out.write("\r\n");
      out.write("          </table>\r\n");
      out.write("          <p align=\"left\"><a href=\"AdminMain.jsp\" class=\"style11\"></a></p>\r\n");
      out.write("          <table width=\"476\" border=\"0\" cellspacing=\"2\" cellpadding=\"2\">\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"468\"><div align=\"left\"><a href=\"AdminMain.jsp\" class=\"style95\">Back</a></div></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("          </table>\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"clr\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      <div class=\"sidebar\">\r\n");
      out.write("        <div class=\"searchform\">\r\n");
      out.write("          <form id=\"formsearch\" name=\"formsearch\" method=\"post\" action=\"#\">\r\n");
      out.write("            <span>\r\n");
      out.write("            <input name=\"editbox_search\" class=\"editbox_search\" id=\"editbox_search\" maxlength=\"80\" value=\"Search our ste:\" type=\"text\" />\r\n");
      out.write("            </span>\r\n");
      out.write("            <input name=\"button_search\" src=\"images/search.gif\" class=\"button_search\" type=\"image\" />\r\n");
      out.write("          </form>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"clr\"></div>\r\n");
      out.write("        <div class=\"gadget\">\r\n");
      out.write("          <h2 class=\"star\"><span>Sidebar</span> Menu</h2>\r\n");
      out.write("          <div class=\"clr\"></div>\r\n");
      out.write("          <ul class=\"sb_menu\">\r\n");
      out.write("            <li><a href=\"AdminMain.jsp\">Home</a></li>\r\n");
      out.write("			<li><a href=\"AdminLogin.jsp\">Logout</a></li>\r\n");
      out.write("			\r\n");
      out.write("            \r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"clr\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"footer\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("<div align=center></div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
