/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.69
 * Generated at: 2023-03-18 07:20:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.util.*;
import java.util.*;
import java.text.*;
import java.util.Date;
import java.sql.*;
import org.bouncycastle.util.encoders.Base64;

public final class User_005fSearchProductsDetails_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/connect.jsp", Long.valueOf(1540290754000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("java.text");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.bouncycastle.util.encoders.Base64");
    _jspx_imports_classes.add("java.util.Date");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<title></title>\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Connection connection = null;
 	try {
     

	  	Class.forName("com.mysql.jdbc.Driver");	
		connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/cc_fraud","root","root");
      	String sql="";

	}
	catch(Exception e)
	{
		System.out.println(e);
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>Searched Product Details</title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/coin-slider.css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/cufon-yui.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/cufon-quicksand.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-1.4.2.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/script.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/coin-slider.min.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("<!--\r\n");
      out.write(".style1 {\r\n");
      out.write("	font-size: 24px;\r\n");
      out.write("	color: #FF0000;\r\n");
      out.write("}\r\n");
      out.write(".style2 {color:#000000}\r\n");
      out.write(".style3 {color:#FF3300}\r\n");
      out.write(".style4 {color: #FFFFFF}\r\n");
      out.write(".style5 {color: #660000}\r\n");
      out.write(".style7 {color:#006666}\r\n");
      out.write(".style8 {color: #FF6600}\r\n");
      out.write(".style9 {font-size: 16px}\r\n");
      out.write(".style10 {font-size: 16px; color: #660000; }\r\n");
      out.write(".style11 {color:#009966}\r\n");
      out.write("-->\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"main\">\r\n");
      out.write("  <div class=\"header\">\r\n");
      out.write("    <div class=\"header_resize\">\r\n");
      out.write("      <div class=\"logo\">\r\n");
      out.write("        <h1 align=\"center\"><a href=\"index.html\" class=\"style1\">Credit card fraud detection using AdaBoost and majority voting</a></h1>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"menu_nav\">\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li class=\"active\"><a href=\"index.html\"><span>Home Page</span></a></li>\r\n");
      out.write("          <li><a href=\"AdminLogin.jsp\"><span>Bank Admin</span></a></li>\r\n");
      out.write("          <li><a href=\"EcommerceLogin.jsp\"><span>Ecommerce</span></a></li>\r\n");
      out.write("          <li><a href=\"UserLogin.jsp\"><span>User</span></a></li>\r\n");
      out.write("          <li><a href=\"#\"><span>Contact Us</span></a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"clr\"></div>\r\n");
      out.write("      <div class=\"slider\">\r\n");
      out.write("        <div id=\"coin-slider\"> <a href=\"#\"><img src=\"images/slide1.jpg\" width=\"935\" height=\"285\" alt=\"\" /> </a> <a href=\"#\"><img src=\"images/slide2.jpg\" width=\"935\" height=\"285\" alt=\"\" /> </a> <a href=\"#\"><img src=\"images/slide3.jpg\" width=\"935\" height=\"285\" alt=\"\" /> </a> </div>\r\n");
      out.write("        <div class=\"clr\"></div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"clr\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"content\">\r\n");
      out.write("    <div class=\"content_resize\">\r\n");
      out.write("      <div class=\"mainbar\">\r\n");
      out.write("        <div class=\"article\"> \r\n");
      out.write("          <h2 class=\"style4\" style=\"color:#CC6600\">Searched Product<span class=\"style11\"> ");
      out.print(request.getParameter("p_Name"));
      out.write("</span>'s Details..</h2>\r\n");
      out.write("          <div class=\"clr\"></div>          \r\n");
      out.write("          <div class=\"post_content\">\r\n");
      out.write("		  <p>&nbsp;</p>\r\n");
      out.write("            ");

					
					try
					{
					String p_Name=request.getParameter("p_Name");
					String p_Category=request.getParameter("p_Category");
					String site=request.getParameter("site");
					
					int rank=Integer.parseInt(request.getParameter("rank"));
					
					int rankup=rank+1;
					
					String uname = (String)application.getAttribute("uname");
					
					String rankUp="update products set rank="+rankup+" where p_name='"+p_Name+"' ";
					connection.createStatement().executeUpdate(rankUp);
			
					String str1="select * from products where p_name='"+p_Name+"' and category='"+p_Category+"' and site='"+site+"' "; 
					Statement st1=connection.createStatement();
					ResultSet rs1=st1.executeQuery(str1);
					while ( rs1.next() )
					{
						int i=rs1.getInt(1);
				
						String model = rs1.getString(6);
						String description = rs1.getString(7);
						String price = rs1.getString(4);
						String date = rs1.getString(9);	
						
							
							/*SimpleDateFormat sdfDate = new SimpleDateFormat("dd/MM/yyyy");
							SimpleDateFormat sdfTime = new SimpleDateFormat("HH:mm:ss");
							
							Date now = new Date();
							String strDate = sdfDate.format(now);
							
							String strTime = sdfTime.format(now);
							String dt = strDate + "   " + strTime;
									   
							String str2 = "insert into postsearch (user,p_name,categorie,keyword,dt) values('"+uname+"','"+p_Name+"','"+p_Categorie+"','"+keyword+"','"+dt+"')";
							connection.createStatement().executeUpdate(str2);
					*/
						
			
      out.write("\r\n");
      out.write("			      <table width=\"598\" border=\"1\" align=\"left\" cellpadding=\"0\" cellspacing=\"0\" >\r\n");
      out.write("                    <tr >\r\n");
      out.write("                      <td width=\"186\" rowspan=\"6\" ><div class=\"style22 style4 style5\" style=\"margin:10px 13px 10px 13px;\" >\r\n");
      out.write("                          <div align=\"center\"><a class=\"#\" id=\"img1\" href=\"#\" >\r\n");
      out.write("                            <input  name=\"image\" type=\"image\" src=\"get_Pic.jsp?picture=");
      out.print("productimage");
      out.write("&id=");
      out.print(i);
      out.write("\" style=\"width:160px; height:250px;\" />\r\n");
      out.write("                          </a> </div>\r\n");
      out.write("                      </div></td>\r\n");
      out.write("                      <td height=\"39\" ><div align=\"center\" class=\"style3 style73\"><span class=\"style10\">Category </span></div></td>\r\n");
      out.write("                      <td width=\"307\"><div align=\"center\" class=\"style3\"><b>");
      out.print( p_Category);
      out.write("</b></div></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr >\r\n");
      out.write("                      <td height=\"37\" ><div align=\"center\" class=\"style10\"> Price </div></td>\r\n");
      out.write("                      <td><div align=\"center\" class=\"style2\"><b>");
      out.print( price);
      out.write(" Rs/-</b></div></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr >\r\n");
      out.write("                      <td height=\"47\" ><div align=\"center\" class=\"style10\">Model</div></td>\r\n");
      out.write("                     <td><div align=\"center\" class=\"style7\"><b>");
      out.print( model);
      out.write("</b></div></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr >\r\n");
      out.write("                      <td height=\"47\" ><div align=\"center\" class=\"style10\"> Description </div></td>\r\n");
      out.write("                      <td><div align=\"center\" class=\"style3\"></div>\r\n");
      out.write("                      \r\n");
      out.write("                        \r\n");
      out.write("                              <div align=\"center\"><span class=\"style3\">\r\n");
      out.write("                              <textarea name=\"textarea\" cols=\"40\" rows=\"8\">");
      out.print( description);
      out.write("</textarea>\r\n");
      out.write("                      </span></div></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr >\r\n");
      out.write("                      <td height=\"46\" ><div align=\"center\" class=\"style10\">Date</div></td>\r\n");
      out.write("                      <td><div align=\"center\" class=\"style2\">");
      out.print( date);
      out.write("</div></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr >\r\n");
      out.write("                      <td width=\"97\" height=\"56\" ></td>\r\n");
      out.write("                      <td><br/>\r\n");
      out.write("					  <form method=\"post\" action=\"User_Payment.jsp\"><label>\r\n");
      out.write("                 \r\n");
      out.write("                    <div align=\"center\">\r\n");
      out.write("					    <input type=\"hidden\" value=\"");
      out.print(p_Name);
      out.write("\" name=\"p_Name\"/>\r\n");
      out.write("					    <input type=\"hidden\" value=\"");
      out.print(p_Category);
      out.write("\" name=\"p_Category\"/>\r\n");
      out.write("						<input type=\"hidden\" value=\"");
      out.print(price);
      out.write("\" name=\"pr\"/>\r\n");
      out.write("						<input type=\"hidden\" value=\"");
      out.print(site);
      out.write("\" name=\"site\"/>\r\n");
      out.write("				       <input type=\"submit\" name=\"Submit3\" value=\"Purchase\" />\r\n");
      out.write("                    </div>\r\n");
      out.write("                 </label></form><br/></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("					 ");

						int a=0;
						String str2="select * from reviews where p_name='"+p_Name+"'  and category='"+p_Category+"'"; 
						Statement st2=connection.createStatement();
						ResultSet rs2=st2.executeQuery(str2);
						while ( rs2.next() )
						{
							String c_user = rs2.getString(4);
							String c_comment = rs2.getString(5);
							String c_date = rs2.getString(6);
							
							
								if(a==0){
					
      out.write("\r\n");
      out.write("					 <tr>\r\n");
      out.write("                       <td valign=\"middle\" height=\"24\" style=\"color: #2c83b0;\"><div align=\"left \" class=\"style15 style11 style71 style77\" style=\"margin-left:20px;\">\r\n");
      out.write("                           <div align=\"center\" class=\"style7 style8\">Reviewed By</div>\r\n");
      out.write("                       </div></td>\r\n");
      out.write("					   <td columnspan=\"2\" valign=\"middle\" height=\"24\" style=\"color: #2c83b0;\"><div align=\"left \" class=\"style15 style11 style71 style77\" style=\"margin-left:20px;\">\r\n");
      out.write("                           <div align=\"center\" class=\"style7 style8\">Date</div>\r\n");
      out.write("					     </div></td>\r\n");
      out.write("					   <td height=\"24\" align=\"center\" valign=\"middle\" style=\"color: #2c83b0;\" columnspan=\"2\"><div align=\"left \" class=\"style15 style11 style71 style77\" style=\"margin-left:20px;\">\r\n");
      out.write("                           <div align=\"center\" class=\"style7 style8\">Review Details</div>\r\n");
      out.write("					     </div></td>\r\n");
      out.write("				    </tr>\r\n");
      out.write("					   ");
a=1;}
      out.write("\r\n");
      out.write("					   <tr>\r\n");
      out.write("                         <td height=\"49\"><div align=\"center\" class=\"style3\" style=\"color:#FF0099\"><b>");
      out.print( c_user);
      out.write("</b></div></td>\r\n");
      out.write("					     <td><div align=\"center\" class=\"style3\" style=\"color:#FF0099\"><b>");
      out.print( c_date);
      out.write("</b></div></td>\r\n");
      out.write("					     <td><div align=\"center\" class=\"style3\" style=\"color:#FF0099\"><b>");
      out.print( c_comment);
      out.write("</b></div></td>\r\n");
      out.write("			        </tr>\r\n");
      out.write("					");
}
      out.write("\r\n");
      out.write("					 <tr>\r\n");
      out.write("                       <td height=\"57\"><div align=\"left \" class=\"style15 style11\" style=\"margin-left:20px;\">\r\n");
      out.write("                           <div align=\"center\" class=\"style87 style10 style5\">Post Your Review </div>\r\n");
      out.write("                       </div></td>\r\n");
      out.write("					   <td colspan=\"2\"><form id=\"form1\" method=\"post\" action=\"User_SubmitReview.jsp\">\r\n");
      out.write("                           <input type=\"text\" name=\"review\" size=\"40\" height=\"30\"/>\r\n");
      out.write("                           <input type=\"hidden\" name=\"p_Name\" value=\"");
      out.print(p_Name);
      out.write("\"/>\r\n");
      out.write("                           <input type=\"hidden\" name=\"p_Category\" value=\"");
      out.print(p_Category);
      out.write("\"/>\r\n");
      out.write("						   <input type=\"hidden\"  name=\"site\" value=\"");
      out.print(site);
      out.write("\"/>\r\n");
      out.write("                           <input type=\"submit\" name=\"Submit\" value=\"Post\" />\r\n");
      out.write("                       </form></td>\r\n");
      out.write("				    </tr>\r\n");
      out.write("	            </table>\r\n");
      out.write("			   \r\n");
      out.write("			      <p>&nbsp;</p>\r\n");
      out.write("			      <p>\r\n");
      out.write("			       ");

		}
		connection.close();
	}
	catch(Exception e)
	{
		out.println(e.getMessage());
	}

      out.write("\r\n");
      out.write("	             </p>\r\n");
      out.write("				   <div align=\"left\">\r\n");
      out.write("				     <p><a href=\"User_SearchProducts.jsp\" class=\"style11\"></a></p>\r\n");
      out.write("				     <p>&nbsp;</p>\r\n");
      out.write("				     <p>&nbsp;</p>\r\n");
      out.write("				     <p>&nbsp;</p>\r\n");
      out.write("				     <p>&nbsp;</p>\r\n");
      out.write("				     <p>&nbsp;</p>\r\n");
      out.write("				     <p>&nbsp;</p>\r\n");
      out.write("				     <p>&nbsp;</p>\r\n");
      out.write("				     <p>&nbsp;</p>\r\n");
      out.write("				     <p>&nbsp;</p>\r\n");
      out.write("				     <p>&nbsp;</p>\r\n");
      out.write("				     <p>&nbsp;</p>\r\n");
      out.write("				     <p>&nbsp;</p>\r\n");
      out.write("				     <p>&nbsp;</p>\r\n");
      out.write("				     <p>&nbsp;</p>\r\n");
      out.write("				     <p>&nbsp;</p>\r\n");
      out.write("				     <p>&nbsp;</p>\r\n");
      out.write("				     <p>&nbsp;</p>\r\n");
      out.write("				     <p align=\"center\"><a href=\"User_SearchProducts.jsp\" class=\"style11\"><strong>Back</strong></a></p>\r\n");
      out.write("				   </div>\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"clr\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      <div class=\"sidebar\">\r\n");
      out.write("        <div class=\"searchform\">\r\n");
      out.write("          <form id=\"formsearch\" name=\"formsearch\" method=\"post\" action=\"#\">\r\n");
      out.write("            <span>\r\n");
      out.write("            <input name=\"editbox_search\" class=\"editbox_search\" id=\"editbox_search\" maxlength=\"80\" value=\"Search our ste:\" type=\"text\" />\r\n");
      out.write("            </span>\r\n");
      out.write("            <input name=\"button_search\" src=\"images/search.gif\" class=\"button_search\" type=\"image\" />\r\n");
      out.write("          </form>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"clr\"></div>\r\n");
      out.write("        <div class=\"gadget\">\r\n");
      out.write("          <h2 class=\"star\"><span>Sidebar</span> Menu</h2>\r\n");
      out.write("          <div class=\"clr\"></div>\r\n");
      out.write("          <ul class=\"sb_menu\">\r\n");
      out.write("           				  <li><a href=\"UserMain.jsp\">Home</a></li>					  \r\n");
      out.write("          				  <li><a href=\"UserLogin.jsp\">Logout </a></li>\r\n");
      out.write("			\r\n");
      out.write("            \r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"clr\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"footer\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("<div align=center></div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
