/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.69
 * Generated at: 2023-03-18 07:20:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.oreilly.servlet.*;
import java.sql.*;
import java.lang.*;
import java.text.SimpleDateFormat;
import java.util.*;
import java.io.*;
import javax.servlet.*;
import javax.servlet.http.*;
import java.sql.*;
import java.util.*;
import java.util.Date;
import javax.crypto.Cipher;
import javax.crypto.spec.SecretKeySpec;
import java.security.KeyPairGenerator;
import java.security.KeyPair;
import java.security.Key;
import org.bouncycastle.util.encoders.Base64;

public final class User_005fSearchProducts_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/connect.jsp", Long.valueOf(1540290754000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("com.oreilly.servlet");
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.lang");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.security.KeyPairGenerator");
    _jspx_imports_classes.add("java.security.Key");
    _jspx_imports_classes.add("java.security.KeyPair");
    _jspx_imports_classes.add("org.bouncycastle.util.encoders.Base64");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("javax.crypto.spec.SecretKeySpec");
    _jspx_imports_classes.add("javax.crypto.Cipher");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("\r\n");
      out.write("<title></title>\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Connection connection = null;
 	try {
     

	  	Class.forName("com.mysql.jdbc.Driver");	
		connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/cc_fraud","root","root");
      	String sql="";

	}
	catch(Exception e)
	{
		System.out.println(e);
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>Search Products</title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/coin-slider.css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/cufon-yui.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/cufon-quicksand.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-1.4.2.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/script.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/coin-slider.min.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("<!--\r\n");
      out.write(".style1 {\r\n");
      out.write("	font-size: 24px;\r\n");
      out.write("	color: #FF0000;\r\n");
      out.write("}\r\n");
      out.write(".style2 {color: #330000}\r\n");
      out.write(".style3 {color:#FF3300}\r\n");
      out.write(".style4 {color: #FFFFFF}\r\n");
      out.write(".style5 {color: #660000}\r\n");
      out.write(".style6 {\r\n");
      out.write("	font-size: 18px;\r\n");
      out.write("	color: #FF0000;\r\n");
      out.write("}-->\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"main\">\r\n");
      out.write("  <div class=\"header\">\r\n");
      out.write("    <div class=\"header_resize\">\r\n");
      out.write("      <div class=\"logo\">\r\n");
      out.write("        <h1 align=\"center\"><a href=\"index.html\" class=\"style1\">Credit card fraud detection using AdaBoost and majority voting</a></h1>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"menu_nav\">\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li class=\"active\"><a href=\"index.html\"><span>Home Page</span></a></li>\r\n");
      out.write("          <li><a href=\"AdminLogin.jsp\"><span>Bank Admin</span></a></li>\r\n");
      out.write("          <li><a href=\"EcommerceLogin.jsp\"><span>Ecommerce</span></a></li>\r\n");
      out.write("          <li><a href=\"UserLogin.jsp\"><span>User</span></a></li>\r\n");
      out.write("          <li><a href=\"#\"><span>Contact Us</span></a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"clr\"></div>\r\n");
      out.write("      <div class=\"slider\">\r\n");
      out.write("        <div id=\"coin-slider\"> <a href=\"#\"><img src=\"images/slide1.jpg\" width=\"935\" height=\"285\" alt=\"\" /> </a> <a href=\"#\"><img src=\"images/slide2.jpg\" width=\"935\" height=\"285\" alt=\"\" /> </a> <a href=\"#\"><img src=\"images/slide3.jpg\" width=\"935\" height=\"285\" alt=\"\" /> </a> </div>\r\n");
      out.write("        <div class=\"clr\"></div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"clr\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"content\">\r\n");
      out.write("    <div class=\"content_resize\">\r\n");
      out.write("      <div class=\"mainbar\">\r\n");
      out.write("        <div class=\"article\"> \r\n");
      out.write("          <h2 class=\"style4\" style=\"color:#CC6600\">Search Products by Keyword..</h2>\r\n");
      out.write("          <div class=\"clr\"></div>          \r\n");
      out.write("          <div class=\"post_content\">\r\n");
      out.write("            <p>&nbsp;</p>\r\n");
      out.write("            <form action=\"User_SearchProducts.jsp\" method=\"post\" id=\"leavereply\">\r\n");
      out.write("                    <p>&nbsp;</p>\r\n");
      out.write("                    <table align=\"center\" style=\"margin:0 0 0 30px;\">\r\n");
      out.write("                      <tr>\r\n");
      out.write("                        <td width=\"174\"><div align=\"center\" class=\"style3\">\r\n");
      out.write("                            <div align=\"right\" class=\"style12\">\r\n");
      out.write("                              <div align=\"center\" class=\"style82\"><b>Enter  Keyword</b></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div></td>\r\n");
      out.write("                        <td width=\"152\"><div align=\"left\">\r\n");
      out.write("                            <input type=\"text\" name=\"keyword\" />\r\n");
      out.write("                        </div></td>\r\n");
      out.write("                        <td width=\"155\"><input name=\"submit\" type=\"submit\" style=\"width:50px; height:25px;\" value=\"GO\"/></td>\r\n");
      out.write("                      </tr>\r\n");
      out.write("                      <tr>\r\n");
      out.write("                        <td colspan=\"3\"><div class=\"style2\">\r\n");
      out.write("                            <div align=\"center\" class=\"style13 style78\"> ( searching content Based on Product Description)</div>\r\n");
      out.write("                        </div></td>\r\n");
      out.write("                      </tr>\r\n");
      out.write("                    </table>\r\n");
      out.write("			        <p class=\"style44\">&nbsp;</p>\r\n");
      out.write("              \r\n");
      out.write("\r\n");
      out.write("              <p align=\"left\"><a href=\"UserMain.jsp\" class=\"style11\">Back</a></p>\r\n");
      out.write("            </form>\r\n");
      out.write("            </div>\r\n");
      out.write("          <div class=\"clr\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"article\">\r\n");
      out.write("          <h2><span class=\"style4\">Products Found.. </span></h2>\r\n");
      out.write("          <div class=\"rf\">\r\n");
      out.write("            <p>\r\n");
      out.write("              ");

  String input="",l_Input="",p_Name="",p_Desc="",p_Desc1="",p_Price="",p_Category="",site=""; 
			int i=0,j=0,k=0,a1=0,rank=0;

try
{	
						String uname = (String)application.getAttribute("uname");
								
								
								input= request.getParameter("keyword");
								if(!input.equals(""))	
								{
								
								l_Input = input.toLowerCase();
		
			SimpleDateFormat sdfDate = new SimpleDateFormat("dd/MM/yyyy");
							SimpleDateFormat sdfTime = new SimpleDateFormat("HH:mm:ss");
							
							Date now = new Date();
							String strDate = sdfDate.format(now);
							
							String strTime = sdfTime.format(now);
							String dt = strDate + "   " + strTime;
								 
								
								String str = "select * from products";
								Statement st=connection.createStatement();
								ResultSet rs = st.executeQuery(str);
								
								while(rs.next())
								{
								    p_Name = rs.getString(2);
									p_Price = rs.getString(4);
									p_Category = rs.getString(3);
									p_Desc = rs.getString(7);  
								    rank   = rs.getInt(10);
									site   = rs.getString(11); 
								
									
								
									p_Desc1 = p_Desc.toLowerCase(); 
									 
									if (p_Desc1.indexOf(l_Input)>=0)
									{
 			
 		  
			String str4 = "insert into productsearch (user,p_name,category,keyword,dt) values('"+uname+"','"+p_Name+"','"+p_Category+"','"+input+"','"+dt+"')";
							connection.createStatement().executeUpdate(str4);
					
		
			
												
									
						if(a1==0)
						{
									
      out.write("\r\n");
      out.write("                    </p>\r\n");
      out.write("				  <p>&nbsp;</p>\r\n");
      out.write("				  <table width=\"506\" border=\"1\" align=\"center\">\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td colspan=\"4\" align=\"center\" class=\"style2\">Results Found in Products</td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td width=\"130\" align=\"center\" valign=\"middle\"><span class=\"style3\">Product Name  </span></td>\r\n");
      out.write("                <td width=\"192\" align=\"center\" valign=\"middle\"><span class=\"style3\">Product Price</span></td>\r\n");
      out.write("                <td width=\"59\" align=\"center\" valign=\"middle\"><span class=\"style3\">Rank</span></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              ");
}a1=1;
      out.write("\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td height=\"55\" align=\"center\" valign=\"middle\"><div align=\"center\" class=\"style5\"><strong>");
      out.print(p_Name);
      out.write("</strong></div></td>\r\n");
      out.write("				<td height=\"55\" align=\"center\" valign=\"middle\"><div align=\"center\" class=\"style5\"><strong>");
      out.print(p_Price);
      out.write("</strong></div></td>\r\n");
      out.write("                \r\n");
      out.write("                <td align=\"center\" valign=\"middle\"><div align=\"center\" class=\"style5\"><strong>");
      out.print(rank);
      out.write("</strong></div></td>\r\n");
      out.write("                <td width=\"97\" height=\"55\"><div align=\"center\">\r\n");
      out.write("                    <p class=\"style50\"><a href=\"User_SearchProductsDetails.jsp?p_Name=");
      out.print(p_Name);
      out.write("&amp;keyword=");
      out.print(l_Input);
      out.write("&amp;p_Category=");
      out.print(p_Category);
      out.write("&amp;rank=");
      out.print(rank);
      out.write("&amp;site=");
      out.print(site);
      out.write("\" class=\"style56 style30\"><strong>View Details</strong></a></p>\r\n");
      out.write("                </div></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              ");
	}
						  
						}
      out.write("\r\n");
      out.write("            </table>\r\n");
      out.write("				 \r\n");
      out.write("					\r\n");
      out.write("            \r\n");
      out.write("           \r\n");
      out.write("             <blockquote>\r\n");
      out.write("						      <p class=\"style72\">\r\n");
      out.write("              ");


				
			
		
		}	
	
		else
		{
			
      out.write("\r\n");
      out.write("            </p>\r\n");
      out.write("            <h3 align=\"center\" class=\"style66 style72 style48\">&nbsp;</h3>\r\n");
      out.write("            <h3 align=\"center\" class=\"style66 style72 style48 style5 style6\">Please Enter Correct Keyword!!</h3>\r\n");
      out.write("            ");

		}
	}
	

catch(Exception e)
{
	e.printStackTrace();
}

      out.write("\r\n");
      out.write("            </p>\r\n");
      out.write("			</blockquote>\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"clr\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      <div class=\"sidebar\">\r\n");
      out.write("        <div class=\"searchform\">\r\n");
      out.write("          <form id=\"formsearch\" name=\"formsearch\" method=\"post\" action=\"#\">\r\n");
      out.write("            <span>\r\n");
      out.write("            <input name=\"editbox_search\" class=\"editbox_search\" id=\"editbox_search\" maxlength=\"80\" value=\"Search our ste:\" type=\"text\" />\r\n");
      out.write("            </span>\r\n");
      out.write("            <input name=\"button_search\" src=\"images/search.gif\" class=\"button_search\" type=\"image\" />\r\n");
      out.write("          </form>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"clr\"></div>\r\n");
      out.write("        <div class=\"gadget\">\r\n");
      out.write("          <h2 class=\"star\"><span>Sidebar</span> Menu</h2>\r\n");
      out.write("          <div class=\"clr\"></div>\r\n");
      out.write("          <ul class=\"sb_menu\">\r\n");
      out.write("           				  <li><a href=\"UserMain.jsp\">Home</a></li>					  \r\n");
      out.write("          				  <li><a href=\"UserLogin.jsp\">Logout </a></li>\r\n");
      out.write("			\r\n");
      out.write("            \r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"clr\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"footer\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("<div align=center></div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
